### PR TITLE
Update sum.py

### PR DESCRIPTION
**Pull request by AshikDavid**

### CODE REVIEW

**Comment by brokenwiings** [comment]
da ninak vere pani onnum illedaaa

**Comment by brokenwiings** [comment]
ideda..thendii

**Comment by AshikDavid** [comment]
Illa

**Comment by brokenwiings** [comment]
;-)

**Comment by AshikDavid** [comment]
Podda

**Comment by brokenwiings** [comment]
podaaaaa...potaaa

**Comment by brokenwiings** [comment]
:-P

**Comment by AshikDavid** [comment]
Need podda potta

**Pull request merged**
